<?php
// Establish database connection
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "stripe_payment";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

require_once('stripe-php/init.php');

\Stripe\Stripe::setApiKey('sk_test_51OApbbDAcRPDvKyQvqu2rHWlX3DA3qLfl0cAPL1DG8gcUS1u91cGcWRKetEzvz8HFggWqKmX7qjFYCIZ6DHjXXae008ZjDxOok'); // Replace 'your_secret_key' with your actual secret key

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $fullName = $_POST["full_name"];
    $address = $_POST["address"];
    $paymentOption = $_POST["payment_option"];
    $stripeToken = $_POST["stripeToken"]; // Token generated by Stripe

    try {
        // Create a charge or perform any Stripe action with the token
        $charge = \Stripe\Charge::create([
            'amount' => 1000, // Replace with the actual amount in cents
            'currency' => 'usd', // Replace with the desired currency
            'description' => 'Example Charge',
            'source' => $stripeToken,
        ]);

        // If successful, you can save the charge information or handle it as needed
        // For example:
        $chargeId = $charge->id; // Get charge ID

        // Now, insert payment details along with the charge ID into the database
        $sql = "INSERT INTO transactions (full_name, address, payment_option, stripe_token) 
                VALUES ('$fullName', '$address', '$paymentOption', '$stripeToken')";

        if ($conn->query($sql) === TRUE) {
            // Display success message
            echo "Payment processed successfully!";

            // Redirect to cart1.php after 3 seconds
            header("refresh:3; url=cart1.php");
            exit; // Stop further execution
        } else {
            echo "Error: " . $sql . "<br>" . $conn->error;
        }
    } catch (\Stripe\Exception\CardException $e) {
        // Handle card errors
        $error = $e->getError();
        // Handle the error appropriately
        echo "Error: " . $error['message'];
    } catch (Exception $e) {
        // Handle other errors
        echo "Error: " . $e->getMessage();
    }
}

// Close the database connection
$conn->close();
?>
